import json
from pathlib import Path
from typing import Any

from app.tools.mcp_base import MCPBaseTool


def _load_sample_backlog() -> list[dict[str, Any]]:
    data_path = Path(__file__).resolve().parents[1] / "data" / "sample_backlog.json"
    return json.loads(data_path.read_text(encoding="utf-8"))


class MockJiraSearchBacklogTool(MCPBaseTool):
    tool_name = "mock_jira.search_backlog"
    display_name = "Mock Jira Backlog Search"
    description = "Searches mock backlog items for related Product Owner work."
    input_schema = {"query": "string", "limit": "integer"}
    output_schema = {"items": "array"}

    def execute(self, tool_input: dict[str, Any]) -> dict[str, Any]:
        query = str(tool_input.get("query", "")).lower()
        limit = int(tool_input.get("limit", 5))
        items = _load_sample_backlog()
        if query:
            terms = [term for term in query.replace("_", " ").split() if len(term) > 2]
            matched = [
                item
                for item in items
                if any(term in f"{item.get('title', '')} {item.get('type', '')} {item.get('status', '')}".lower() for term in terms)
            ]
            if matched:
                items = matched
        return {"items": items[:limit]}


class MockJiraCreateStoryPreviewTool(MCPBaseTool):
    tool_name = "mock_jira.create_story_preview"
    display_name = "Mock Jira Story Preview"
    description = "Creates a deterministic Jira-style story preview without writing to Jira."
    input_schema = {"title": "string", "description": "string", "priority": "string"}
    output_schema = {"story_preview": "object"}

    def execute(self, tool_input: dict[str, Any]) -> dict[str, Any]:
        title = str(tool_input.get("title", "Draft PO Agent story"))
        return {
            "story_preview": {
                "project_key": "POA",
                "issue_type": "Story",
                "summary": title,
                "description": tool_input.get("description", "Generated by mock PO Agent tooling."),
                "priority": tool_input.get("priority", "Medium"),
                "status": "Preview only",
            }
        }


class MockJiraTool(MockJiraSearchBacklogTool):
    def run(self, payload: dict[str, Any]) -> list[dict[str, Any]]:  # Backward-compatible shape.
        return self.execute(payload)["items"]
